version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    volumes:
      - .:/app

    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data:



# version: '3.8'  # or any other version you prefer

# services:
#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: library
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: admin
#     ports:
#       - "5432:5432"
#     volumes:
#       - db-data:/var/lib/postgresql/data

#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     depends_on:
#       - db
#     ports:
#       - "8000:8000"

# volumes:
#   db-data:


